version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_zenpass
      MYSQL_DATABASE: zeninv
      MYSQL_USER: zeninvestor
      MYSQL_PASSWORD: zenpass
    hostname: mysql
    restart: always
    user: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 86:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: zeninvestor
      PMA_PASSWORD: zenpass
    depends_on:
      - mysql
