version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/pgdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_zenpass
      MYSQL_DATABASE: zeninv
      MYSQL_USER: zeninvestor
      MYSQL_PASSWORD: zenpass
    hostname: mysql_db
    restart: always
    user: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "86:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: zeninvestor
      PMA_PASSWORD: zenpass
    volumes:
      - ./docker/pgadmin:/var/lib/phpmyadmin
    depends_on:
      - mysql
